### ISSUE TITLE
Is this still working for you?

### ISSUE THREAD

**Issue by brbeaird** [MathewsTito/myqnode#5]
I have a similar MyQ integration with SmartThings that suddenly stopped working in the last couple days. It looks like Chamberlain changed the API...I can still get a login token but throws an unauthorized error whenever I try and do anything with it.

**Comment by ptmuldoon** [comment]
I honestly do not know and stop using this here along time ago.  I've been using both OpenHab and HomeAssistant, and both have bindings, etc that work with it, or at least did.  I mainly only keep track of a zwave sensor on the door for status, and have the MyQ app as well if really need to check and open/close the door.

**Comment by brbeaird** [comment]
Gotcha, thanks! I figured out my issue - I needed to start sending the token in the header for the get device call.
